import Navbar from '@/components/NavBar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import { ThemeProvider } from '@/context/ThemeContext'
import AuthProvider from '@/components/AuthProvider/AuthProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: ' Ashraf Abir Full Stack App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider>
        <AuthProvider>
        <div className="container">

        
       <Navbar/>
        {children}
        <Footer/>
        </div>
        </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
